language: java

sudo: false

dist: trusty

addons:
  apt:
    packages:
      - openjdk-6-jdk
  sonarcloud:
    organization: "saeg"

jdk:
  - openjdk10
  - oraclejdk9
  - openjdk7

matrix:
  include:
    - jdk: oraclejdk8
      env: $RUN_SONAR=true
    - jdk: oraclejdk8
      env: $JDK=6

before_install:
  - if [[ "$JDK" = "6" ]]; then jdk_switcher use openjdk6; fi
  - java -Xmx32m -version
  - javac -J-Xmx32m -version

install: true

script: ./mvnw verify

after_success:
  - ./mvnw coveralls:report
  - if [ "$RUN_SONAR" = true ]; then ./mvnw sonar:sonar; fi

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.m2/wrapper'
    - '$HOME/.sonar/cache'
