language: java

sudo: false

dist: trusty

addons:
  apt:
    packages:
      - openjdk-6-jdk
  sonarcloud:
    organization: "saeg"

jdk:
  - openjdk10
  - oraclejdk9
  - openjdk7
  - openjdk6

matrix:
  include:
    - jdk: oraclejdk8
      env: $RUN_SONAR=true

install: true

script: ./mvnw verify -s .mvn/settings.xml

after_success:
  - ./mvnw coveralls:report -s .mvn/settings.xml
  - if [ "$RUN_SONAR" = true ]; then ./mvnw sonar:sonar; fi

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.m2/wrapper'
    - '$HOME/.sonar/cache'
